#!/usr/bin/env python3
"""Browser checks over real HTTP; also test the public serving boundary.
UI correctness is not a certification of scholarly content or repository privacy.
"""
import argparse,hashlib,io,json,pathlib,time,urllib.error,urllib.request
from PIL import Image
from playwright.sync_api import sync_playwright

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--url',required=True);ap.add_argument('--out',default='build/garden-qa');ap.add_argument('--executable');ap.add_argument('--skip-boundary',action='store_true');args=ap.parse_args()
    dest=pathlib.Path(args.out);dest.mkdir(parents=True,exist_ok=True);checks=[];errors=[]
    def check(name,ok,detail=None):
        checks.append({'name':name,'passed':bool(ok),'detail':detail})
        if not ok:raise AssertionError(name+': '+str(detail))
    with sync_playwright() as p:
        opts={'headless':True}
        if args.executable:opts['executable_path']=args.executable
        browser=p.chromium.launch(**opts);context=browser.new_context(viewport={'width':1440,'height':1060},device_scale_factor=1)
        page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto(args.url+'?lang=zh',wait_until='networkidle',timeout=60000)
        check('Homepage visible',page.locator('.hero-copy h1').is_visible())
        check('Six visual exploration portals',page.locator('#heroPortalDeck .portal-card').count()==6)
        check('Gamified journey entry visible',page.locator('#journeyButton').is_visible())
        page.locator('#journeyButton').click();page.wait_for_timeout(80);check('Accessible journey dialog opens',page.locator('#journeyDialog').evaluate('e=>e.open') and page.locator('.stamp-grid .stamp').count()==6);page.locator('[data-close-journey]').click();page.wait_for_timeout(40)
        check('Garden PNG loaded',page.request.get(args.url+'assets/garden.png').status==200)
        check('Cinematic v4 release marker',page.locator('meta[name="dharma-ui-release"]').get_attribute('content')=='cinematic-4.0')
        expected_assets=json.loads(pathlib.Path('build/garden-release.json').read_text()).get('cinematic_asset_sha256',{}) if pathlib.Path('build/garden-release.json').exists() else {}
        for name in ['sacred-world.webp','sacred-world-mobile.webp','map.webp','texts.webp','places.webp','people.webp','timeline.webp','library.webp']:
            response=page.request.get(args.url+'assets/'+name)
            check('Cinematic asset served: '+name,response.status==200)
            raw_image=response.body()
            im=Image.open(io.BytesIO(raw_image));im.load()
            check('Cinematic asset decoded: '+name,im.width>=200 and im.height>=100)
            if name=='sacred-world.webp':check('Hero retained at full resolution',im.width>=1700 and im.height>=850,list(im.size))
            if name in expected_assets:check('Exact published image bytes: '+name,hashlib.sha256(raw_image).hexdigest()==expected_assets[name])
        check('Actual hero uses cinematic raster', 'sacred-world.webp' in page.locator('.hero-scene').evaluate('e=>getComputedStyle(e).backgroundImage'))
        page.locator('#heroDiscoveryQuery').fill('Buddha');page.locator('#heroSearchButton').click()
        check('Cross-entity search opens',page.locator('#discoveryDialog').evaluate('e=>e.open'))
        check('Search includes real people',page.locator('#discoveryResults [data-record="person"]').count()>0)
        page.locator('#discoveryResults [data-record="person"]').first.click()
        check('Search opens a real person record',page.locator('#modal').evaluate('e=>e.open') and len(page.locator('#modalTitle').inner_text())>0)
        page.locator('#closeModal').click()
        page.locator('.scene-hotspots [data-record="person"]').click()
        check('Scene hotspot opens Buddha record',page.locator('#modal').evaluate('e=>e.open') and '释迦' in page.locator('#modalTitle').inner_text())
        page.locator('#closeModal').click()
        page.locator('#journeyButton').click()
        check('A discovery lights a stamp',page.locator('.stamp.earned').count()>=1)
        page.locator('[data-draw-card]').click();card_title=page.locator('.explore-card h3').inner_text()
        check('Daily learning card renders',bool(card_title))
        page.locator('[data-close-journey]').click()
        page.locator('.journey-orb').click()
        check('Real guided tour opens',page.locator('#modal .guide-step').inner_text().endswith('1 / 4'))
        page.locator('#modal [data-guide="1"]').click()
        check('Tour advances to next step',page.locator('#modal .guide-step').inner_text().endswith('2 / 4'))
        page.locator('#closeModal').click()
        page.locator('#quietButton').click()
        check('Quiet view reveals artwork',page.locator('.garden-hero').evaluate('e=>e.classList.contains("quiet-view")'))
        page.keyboard.press('Escape')
        check('Escape restores the interface',not page.locator('.garden-hero').evaluate('e=>e.classList.contains("quiet-view")'))
        page.reload(wait_until='networkidle');page.locator('#journeyButton').click()
        check('Exploration and daily card persist',page.locator('.stamp.earned').count()>=1 and page.locator('.explore-card h3').inner_text()==card_title)
        page.locator('[data-toggle-motion]').click()
        check('Motion can be paused',page.locator('body').evaluate('e=>e.classList.contains("no-motion")'))
        page.locator('[data-toggle-motion]').click();page.locator('[data-close-journey]').click()
        content=page.eval_on_selector('#public-content','e=>JSON.parse(e.textContent)')
        check('100 texts preserved',len(content['works'])==100)
        check('12 bilingual stories',len(content['stories'])==12 and all(len(s['body_en'])>350 and len(s['body_zh'])>100 for s in content['stories']))
        raw=json.dumps(content,ensure_ascii=False)
        check('No raw research or own-repository identifiers',not any(x.lower() in raw.lower() for x in ['minyajing-rgb','github.com','githubusercontent.com','review_flags','source_commit','canonical_datasets','DA-W-','WIT-']))
        check('No repository links in homepage',page.locator('a[href*="github"]').count()==0)
        page.screenshot(path=str(dest/'desktop-home.png'),full_page=True)
        page.screenshot(path=str(dest/'desktop-first-screen.png'))
        def route(h):
            page.evaluate('(h)=>location.hash=h',h)
            page.locator('#'+h).wait_for(state='visible')
            page.wait_for_timeout(80)
        def close():
            if page.locator('#modal').evaluate('e=>e.open'):page.locator('#closeModal').click()
        route('works');check('First page has 18 text cards',page.locator('#workGrid .work-card').count()==18)
        page.locator('#workQuery').fill('心经');check('Chinese search',page.locator('#workGrid').inner_text().find('般若波罗蜜多心经')>=0)
        page.locator('#workGrid [data-act="work"]').first.click();check('Text details open',page.locator('#modal').evaluate('e=>e.open'));close()
        page.locator('#workQuery').fill('SN 56.11');check('Catalogue number search',page.locator('#workGrid .work-card').count()>=1)
        page.locator('#workQuery').fill('');page.locator('#evidenceFilter').select_option('books');check('Bibliography filter',str(sum(bool(w['books']) for w in content['works'])) in page.locator('#workCount').inner_text())
        page.locator('#evidenceFilter').select_option('objects');check('Object filter',page.locator('#workGrid .work-card').count()==sum(bool(w['objects']) for w in content['works']))
        page.locator('#evidenceFilter').select_option('all');page.locator('[data-choose]').nth(0).check();page.locator('[data-choose]').nth(1).check();page.locator('[data-act="compare"]').click();check('Two-text comparison',page.locator('.compare-grid .card').count()==2);close();page.locator('[data-act="clear"]').click()
        page.locator('#workGrid [data-act="bookmark"]').first.click();page.locator('#savedOnly').check();check('Bookmark filtering',page.locator('#workGrid .work-card').count()==1);page.reload(wait_until='networkidle');page.locator('#savedOnly').check();check('Bookmark persists after refresh',page.locator('#workGrid .work-card').count()==1);page.locator('#savedOnly').uncheck()
        page.evaluate('for (const w of A.works) { showWork(w.id); if (!document.getElementById("modalTitle").textContent) throw Error(w.id); closeModal(); }')
        check('All 100 text details render',not errors,errors)
        route('stories');check('12 story cards render',page.locator('#storyGrid .story-card').count()==12);page.locator('#storyGrid [data-act="story"]').first.click();check('Story has full body',len(page.locator('.prose').inner_text())>100);page.locator('[data-act="read"]').click();close();page.reload(wait_until='networkidle');check('Reading progress persists', '1 / 12' in page.locator('#readingStatus').inner_text())
        route('atlas');check('Seven sourced events',page.locator('#eventList .event').count()==7);page.locator('#yearRange').fill('868');check('Year slider uses dated events',page.locator('#eventList .event').count()==2);page.locator('[data-tab="map"][data-value="libraries"]').click();check('Modern libraries separated from ancient dates',page.locator('#yearRange').is_disabled() and page.locator('#placeButtons button').count()==17)
        route('people');check('People collection retained',page.locator('#peopleGrid .card').count()==len(content['people']))
        route('library');check('Object collection retained',page.locator('#libraryGrid .card').count()==len(content['objects']));page.locator('[data-tab="library"][data-value="figures"]').click();check('Six visual guides',page.locator('.library-figure').count()==6)
        for f in content['figures']:check('Guide asset: '+f['id'],page.request.get(args.url+f['src'].removeprefix('./')).status==200)
        route('about');check('33 public method cards',page.locator('#aboutBody .card').count()==33);page.locator('[data-tab="about"][data-value="sources"]').click();check('Institutional sources retained',page.locator('#aboutBody .card').count()==len(content['sources']))
        route('home');page.locator('#langToggle').click();check('English is separately selectable',page.locator('html').get_attribute('lang')=='en' and 'lang=en' in page.url)
        check('English homepage copy', 'Dharma Atlas' in page.locator('.hero-copy').inner_text() and 'Places · People · Wisdom' in page.locator('.hero-copy').inner_text())
        page.screenshot(path=str(dest/'desktop-english.png'))
        route('stories');page.locator('#storyGrid [data-act="story"]').first.click();check('English story body', 'shared memory' in page.locator('.prose').inner_text());close()
        route('works');page.locator('#workQuery').fill('Heart Sutra');check('English transliteration search',page.locator('#workGrid .work-card').count()>=1)
        page.locator('#workGrid [data-act="work"]').first.click();check('English text details', 'A place to start' in page.locator('#modalBody').inner_text());close()
        page.locator('#langToggle').click();route('home')
        for width in [390,360]:
            page.set_viewport_size({'width':width,'height':844});route('home');check('Mobile homepage no overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
            page.locator('#menuToggle').click();page.locator('#nav').wait_for(state='visible');check('Mobile navigation opens '+str(width),page.locator('#nav').is_visible())
            page.locator('#nav a[href="#works"]').click();page.locator('#works').wait_for(state='visible');check('Mobile navigation works '+str(width),page.locator('#works').is_visible())
            page.locator('#workQuery').fill('');page.locator('#workGrid [data-act="work"]').first.click();check('Mobile dialog fits '+str(width),page.locator('#modal').bounding_box()['width']<=width);close();route('atlas');check('Mobile map no overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.set_viewport_size({'width':390,'height':844});route('home');page.screenshot(path=str(dest/'mobile-home.png'),full_page=True);page.screenshot(path=str(dest/'mobile-first-screen.png'))
        check('No JavaScript errors',not errors,errors)
        check('No backend/export links added by interactions',page.locator('a[href*="github"],a[href$=".json"]').count()==0)
        if not args.skip_boundary:
            for path in ['data/CURRENT.json','review/index.html','release.json','public_deployment.json','archive/pre-public-beta/index.html','research_audit_v0.7.json']:
                response=page.request.get(args.url+path)
                check('Internal path not served: '+path,response.status==404,response.status)
        browser.close()
    report={'url':args.url,'passed':sum(c['passed'] for c in checks),'total':len(checks),'checks':checks,'javascript_errors':errors,'tested_at':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),'limits':['UI and serving-boundary tests are not scholarly certification.','Public repository visibility is unchanged.','Existing third-party source links are not all live-checked.']}
    (dest/'qa.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='checks'},ensure_ascii=False))
if __name__=='__main__':main()
